import { scenario } from '../data/scenario';
import { molecular, type MolecularAnswer, type MolecularScenario } from '../data/molecular';
import { sample, digitalCodeFor, type SampleScenario } from '../data/sample';
import { incident } from '../data/incident';
import { InteractiveObject } from '../interaction/InteractiveObject';
import type { TrainingSnapshot } from '../training/TrainingState';
import type { VerificationResult } from '../training/Mission2Manager';
import type { MolecularResult } from '../training/Mission4Manager';
import type { WasteCategory } from '../data/incident';

export class UIManager {
  readonly root: HTMLElement; private modal!: HTMLElement; private prompt!: HTMLElement; private targetLabel!: HTMLElement; private missionToast!: HTMLElement; private pointerHint!: HTMLElement;
  constructor(container: HTMLElement) { this.root = document.createElement('div'); this.root.className = 'ui'; container.append(this.root); this.root.innerHTML = `<section class="start-screen"><div class="eyebrow">SIMULADOR EDUCATIVO</div><h1>${scenario.title}</h1><p>Capacitación inmersiva para estudiantes de ciencias de la salud.</p><div class="module">MÓDULO 01<br><strong>${scenario.module}</strong></div><button class="primary start">INICIAR CAPACITACIÓN</button><small>Demo educativo. No contiene material biológico real ni procedimientos experimentales.</small></section><section class="game-ui hidden"><div class="hud"><span class="eyebrow">MISIÓN 1/5</span><strong>${scenario.mission}</strong><span class="objective">Complete las condiciones necesarias para ingresar.</span></div><div class="crosshair">+</div><div class="interaction"><span class="target"></span><span class="prompt">[E] Interactuar</span></div><div class="controls">WASD mover · Mouse mirar · E interactuar · ESC liberar cursor</div><div class="pointer-hint">Haz clic en la escena para recuperar el control del cursor.</div><div class="toast"></div></section>`; this.modal = document.createElement('div'); this.modal.className = 'modal-layer hidden'; this.root.append(this.modal); this.prompt = this.root.querySelector('.prompt') as HTMLElement; this.targetLabel = this.root.querySelector('.target') as HTMLElement; this.missionToast = this.root.querySelector('.toast') as HTMLElement; this.pointerHint = this.root.querySelector('.pointer-hint') as HTMLElement; }
  onStart(callback: () => void): void { this.root.querySelector('.start')?.addEventListener('click', callback); }
  showGame(): void { this.root.querySelector('.start-screen')?.classList.add('hidden'); this.root.querySelector('.game-ui')?.classList.remove('hidden'); }
  setMission(snapshot: TrainingSnapshot): void { if (!snapshot.mission1Completed) return; const eyebrow = this.root.querySelector('.hud .eyebrow'); const title = this.root.querySelector('.hud strong'); const objective = this.root.querySelector('.objective'); if (snapshot.mission4Completed) { if (eyebrow) eyebrow.textContent = 'MISIÓN 5/5'; if (title) title.textContent = snapshot.mission5Completed ? 'Completada' : 'Incidente y finalización'; if (objective) objective.textContent = snapshot.mission5Completed ? 'Misión 5 completada.' : 'Reconozca la situación, reporte el incidente y complete el cierre.'; } else if (snapshot.mission3Completed) { if (eyebrow) eyebrow.textContent = 'MISIÓN 4/5'; if (title) title.textContent = snapshot.mission4Completed ? 'Completada' : 'Diagnóstico molecular'; if (objective) objective.textContent = snapshot.mission4Completed ? 'Misión 4 completada.' : 'Complete el análisis conceptual e interprete correctamente el resultado.'; } else if (snapshot.mission2Completed) { if (eyebrow) eyebrow.textContent = 'MISIÓN 3/5'; if (title) title.textContent = snapshot.mission3Completed ? 'Completada' : scenario.mission3; if (objective) objective.textContent = snapshot.mission3Completed ? 'Misión 3 completada.' : 'Reconozca los elementos del área y mantenga un flujo de trabajo seguro.'; } else { if (eyebrow) eyebrow.textContent = 'MISIÓN 2/5'; if (title) title.textContent = 'Recepción y verificación'; if (objective) objective.textContent = 'Localice SIM-001 y verifique su información.'; } }
  setMission5(snapshot: TrainingSnapshot): void { this.setMission(snapshot); }
  setTarget(target: InteractiveObject | null): void { this.prompt.classList.toggle('visible', Boolean(target)); this.targetLabel.textContent = target ? `${target.name} · ` : ''; }
  setPointerHint(visible: boolean): void { this.pointerHint.classList.toggle('visible', visible); }
  showSafety(done: () => void): void { this.showModal(`<div class="eyebrow">INFORMACIÓN DE SEGURIDAD</div><h2>Área de ingreso</h2><p>Escenario educativo de laboratorio clínico.</p><p>Antes de ingresar deben revisarse los riesgos y las medidas de seguridad establecidas para la actividad.</p><ul>${scenario.safetyRisks.map((risk) => `<li>${risk}</li>`).join('')}</ul><button class="primary modal-action">ENTENDIDO</button>`, done); }
  showPreparation(done: () => void): void { this.showModal(`<div class="eyebrow">PREPARACIÓN PERSONAL</div><h2>Condiciones de preparación</h2><p>Complete las condiciones de preparación definidas antes del ingreso.</p><div class="prep-items"><span>Protección visual</span><span>Bata</span><span>Guantes simulados</span></div><button class="primary modal-action">COMPLETAR PREPARACIÓN</button>`, done); }
  showHandHygiene(done: () => void): void { this.showModal('<div class="eyebrow">HIGIENE DE MANOS</div><h2>Estación de higiene de manos</h2><p>Acción de entrenamiento registrada.</p><div class="loader"></div>', undefined); window.setTimeout(() => { this.closeModal(); done(); }, 2000); }
  showDoor(snapshot: TrainingSnapshot, unlock: () => void): void { const check = (value: boolean, label: string) => `<li class="${value ? 'done' : 'pending'}">${value ? '✓' : '×'} ${label}</li>`; const all = snapshot.riskInfoReviewed && snapshot.preparationCompleted && snapshot.handHygieneCompleted; this.showModal(`<div class="eyebrow">VERIFICACIÓN DE INGRESO</div><h2>${all ? 'ACCESO HABILITADO' : 'Requisitos pendientes'}</h2><ul class="checks">${check(snapshot.riskInfoReviewed, 'Información revisada')}${check(snapshot.preparationCompleted, 'Preparación completada')}${check(snapshot.handHygieneCompleted, 'Higiene registrada')}</ul>${all ? '<button class="primary modal-action">ABRIR PUERTA</button>' : '<p class="warning">Complete las condiciones pendientes.</p>'}`, all ? unlock : undefined); }
  showSample(done: () => void): void { this.showModal(`<div class="eyebrow">MUESTRA DE ENTRENAMIENTO</div><h2>Identificación de SIM-001</h2><dl><dt>Código</dt><dd>${sample.physicalCode}</dd><dt>Tipo</dt><dd>${sample.type}</dd><dt>Solicitud</dt><dd>${sample.request}</dd><dt>Estado</dt><dd>Pendiente de verificación</dd></dl><button class="primary modal-action">REGISTRAR INFORMACIÓN REVISADA</button>`, done); }
  showInspectionBlocked(): void { this.showModal('<h2>VERIFICACIÓN INCOMPLETA</h2><p>Complete la Misión 1 antes de inspeccionar la muestra.</p>'); }
  showComputer(kind: SampleScenario, onDecision: (decision: 'accept' | 'report_discrepancy') => void): void { const code = digitalCodeFor(kind); this.showModal(`<div class="eyebrow">SISTEMA DE LABORATORIO</div><h2>Registro de recepción</h2><dl><dt>Paciente</dt><dd>${sample.patient}</dd><dt>Código</dt><dd>${code}</dd><dt>Tipo</dt><dd>${sample.type}</dd><dt>Solicitud</dt><dd>${sample.request}</dd></dl><div class="decision-buttons"><button class="primary accept">ACEPTAR MUESTRA</button><button class="secondary report">REPORTAR DISCREPANCIA</button></div>`); this.modal.querySelector('.accept')?.addEventListener('click', () => { this.closeModal(); onDecision('accept'); }); this.modal.querySelector('.report')?.addEventListener('click', () => { this.closeModal(); onDecision('report_discrepancy'); }); }
  showVerificationResult(result: VerificationResult): void { this.showModal(result.correct ? '<h2>MISIÓN 2 COMPLETADA</h2><p>Verificación correcta.</p>' : '<h2>DECISIÓN INCORRECTA</h2><p>Revise nuevamente la muestra y el registro.</p>'); }
  showConceptReview(title: string, body: string, button: string, done: () => void): void { this.showModal(`<div class="eyebrow">RECONOCIMIENTO EDUCATIVO</div><h2>${title}</h2><p>${body}</p><button class="primary modal-action">${button}</button>`, done); }
  showContamination(done: () => void): void { this.showConceptReview('CONTAMINACIÓN CRUZADA SIMULADA', 'SIM-001 → Mano virtual → Teclado. La secuencia trasladó contaminación simulada hacia una superficie compartida.', 'RECONOCER ERROR', done); }
  showSafeFlow(done: () => void): void { this.showConceptReview('FLUJO SEGURO', 'La secuencia evitó trasladar contaminación simulada hacia la superficie compartida.', 'CONTINUAR', done); }
  showMission3Result(message: string): void { this.showModal(`<h2>${message}</h2><p>Trabajo seguro y prevención de contaminación.</p>`); }
  showMolecularRecognition(done: () => void): void { this.showConceptReview(molecular.equipment, `SISTEMA MOLECULAR SIMULADO · Caso ${molecular.caseId} · Solicitud ${molecular.request}. Equipo ficticio para actividad educativa.`, 'REGISTRAR RECONOCIMIENTO', done); }
  showMolecularStart(done: () => void): void { this.showConceptReview(molecular.equipment, `Caso ${molecular.caseId}. Ensayo ${molecular.request}. Estado: preparado para simulación.`, 'INICIAR ANÁLISIS SIMULADO', done); }
  showAnalysisProgress(done: () => void): void { this.showModal(`<h2>${molecular.equipment}</h2><p>Muestra simulada → Procesamiento conceptual → Detección → Análisis</p><div class="analysis-bar"><span></span></div>`); window.setTimeout(() => { this.closeModal(); done(); }, 2200); }
  showMolecularResult(kind: MolecularScenario, onReview: () => void): void { const result = kind === 'valid' ? '<p>Influenza A: <b>DETECTADO</b></p><p>Influenza B: <b>NO DETECTADO</b></p><p>Control: <b>VÁLIDO</b></p>' : '<p>Influenza A: —</p><p>Influenza B: —</p><p>Control: <b>NO VÁLIDO</b></p><p>Resultado: <b>INVÁLIDO</b></p>'; this.showModal(`<h2>RESULTADO SIMULADO — SIM-001</h2>${result}<button class="primary modal-action">REVISAR INTERPRETACIÓN</button>`, onReview); }
  showMolecularQuestion(kind: MolecularScenario, onAnswer: (answer: MolecularAnswer) => void): void { const content = kind === 'valid' ? '<h2>¿QUÉ INDICA PRINCIPALMENTE ESTE RESULTADO?</h2><button class="secondary answer" data-answer="detected_target">A. Se detectó material genético del objetivo.</button><button class="secondary answer" data-answer="viable_virus">B. Existe necesariamente virus viable.</button><button class="secondary answer" data-answer="no_other_infection">C. No puede existir otra infección.</button><button class="secondary answer" data-answer="discard_result">D. Debe descartarse automáticamente.</button>' : '<h2>¿DEBE INTERPRETARSE COMO RESULTADO NEGATIVO?</h2><button class="secondary answer" data-answer="invalid_yes">SÍ</button><button class="secondary answer" data-answer="invalid_no">NO</button>'; this.showModal(content); this.modal.querySelectorAll<HTMLButtonElement>('.answer').forEach((button) => button.addEventListener('click', () => { this.closeModal(); onAnswer(button.dataset.answer as MolecularAnswer); })); }
  showMolecularInterpretation(result: MolecularResult): void { const content = result.correct ? result.reason === 'valid_interpretation' ? '<h2>INTERPRETACIÓN CORRECTA</h2><p>La simulación indica detección del objetivo molecular evaluado. Esto no permite concluir viabilidad viral ni descartar otras condiciones clínicas.</p>' : '<h2>INTERPRETACIÓN CORRECTA</h2><p>El resultado no cumple criterios de validez. No debe interpretarse como negativo válido. Siga el procedimiento institucional correspondiente.</p>' : '<h2>INTERPRETACIÓN INCORRECTA</h2><p>Revise nuevamente el significado del resultado en esta simulación.</p>'; this.showModal(content); }
  showMolecularBlocked(): void { this.showModal('<h2>SECUENCIA INCOMPLETA</h2><p>Complete el análisis simulado antes de consultar el resultado.</p>'); }
  showMission4Result(): void { this.showModal('<h2>MISIÓN 4 COMPLETADA</h2><p>Interpretación molecular realizada correctamente.</p>'); }
  setMission5State(_snapshot: TrainingSnapshot): void { }
  showIncident(onDecision: (decision: 'acknowledge' | 'continue_work' | 'ignore') => void): void { this.showModal(`<div class="eyebrow">⚠ INCIDENTE SIMULADO</div><h2>Condición anormal detectada</h2><p>Seleccione cómo proceder.</p><button class="primary incident" data-decision="acknowledge">RECONOCER INCIDENTE</button><button class="secondary incident" data-decision="continue_work">CONTINUAR TRABAJANDO</button><button class="secondary incident" data-decision="ignore">IGNORAR</button>`); this.modal.querySelectorAll<HTMLButtonElement>('.incident').forEach((button) => button.addEventListener('click', () => { this.closeModal(); onDecision(button.dataset.decision as 'acknowledge' | 'continue_work' | 'ignore'); })); }
  showIncidentMessage(title: string, body: string): void { this.showModal(`<h2>${title}</h2><p>${body}</p>`); }
  showReport(done: () => void): void { this.showConceptReview('REPORTE DE INCIDENTE', `Caso: ${incident.caseId}. Área: ${incident.area}. Estado: pendiente de reporte.`, 'REPORTAR INCIDENTE', done); }
  showEmergency(done: () => void): void { this.showConceptReview('ESTACIÓN DE EMERGENCIA', 'Punto de referencia para recursos y acciones institucionales de respuesta.', 'REGISTRAR RECONOCIMIENTO', done); }
  showWasteItem(label: string, onAnswer: (category: WasteCategory) => void): void { this.showModal(`<h2>Elemento: ${label}</h2><p>Seleccione la categoría conceptual.</p><button class="secondary waste" data-category="general">RESIDUO GENERAL</button><button class="secondary waste" data-category="simulated_biological">RESIDUO BIOLÓGICO SIMULADO</button><button class="secondary waste" data-category="simulated_sharps">CORTOPUNZANTE SIMULADO</button>`); this.modal.querySelectorAll<HTMLButtonElement>('.waste').forEach((button) => button.addEventListener('click', () => { this.closeModal(); onAnswer(button.dataset.category as WasteCategory); })); }
  showWasteIncorrect(retry: () => void): void { this.showModal('<h2>CLASIFICACIÓN INCORRECTA</h2><p>Revise la categoría conceptual del elemento.</p><button class="primary modal-action">REINTENTAR</button>', retry); }
  showWasteComplete(): void { this.showModal('<h2>GESTIÓN DE RESIDUOS COMPLETADA</h2><p>Los elementos simulados fueron clasificados correctamente.</p>'); }
  showCloseout(snapshot: TrainingSnapshot, confirm: () => void): void { const check = (value: boolean, text: string) => `<li class="${value ? 'done' : 'pending'}">${value ? '✓' : '×'} ${text}</li>`; const ready = snapshot.mission4Completed && snapshot.incidentAcknowledged && snapshot.unsafeActivityStopped && snapshot.incidentReported && snapshot.emergencyStationReviewed && snapshot.wasteClassificationCompleted; this.showModal(`<h2>VERIFICACIÓN DE CIERRE</h2><ul class="checks">${check(snapshot.mission4Completed, 'Misión 4 completada')}${check(snapshot.incidentAcknowledged, 'Incidente reconocido')}${check(snapshot.unsafeActivityStopped, 'Actividad detenida')}${check(snapshot.incidentReported, 'Incidente reportado')}${check(snapshot.emergencyStationReviewed, 'Estación revisada')}${check(snapshot.wasteClassificationCompleted, 'Residuos gestionados')}</ul>${ready ? '<button class="primary modal-action">CONFIRMAR VERIFICACIÓN</button>' : '<p class="warning">EXISTE UNA ACTIVIDAD PENDIENTE</p>'}`, ready ? confirm : undefined); }
  showFinalize(done: () => void): void { this.showConceptReview('CIERRE VERIFICADO', 'Todos los requisitos están completos.', 'FINALIZAR CAPACITACIÓN', done); }
  showMission5Complete(): void { this.missionToast.innerHTML = '<strong>MISIÓN 5 COMPLETADA</strong><span>Actividad finalizada correctamente dentro de la simulación.</span>'; this.missionToast.classList.add('visible'); }
  showComplete(): void { this.showModal('<h2>MISIÓN 1 COMPLETADA</h2><p>Ingreso seguro al laboratorio.</p>'); }
  private showModal(content: string, action?: () => void): void { this.modal.innerHTML = `<div class="modal">${content}<button class="close">Cerrar</button></div>`; this.modal.classList.remove('hidden'); this.modal.querySelector('.close')?.addEventListener('click', () => this.closeModal()); if (action) this.modal.querySelector('.modal-action')?.addEventListener('click', () => { this.closeModal(); action(); }); }
  private closeModal(): void { this.modal.classList.add('hidden'); this.modal.innerHTML = ''; }
}
