import { CollisionSystem } from '../player/CollisionSystem';
import { PlayerController } from '../player/PlayerController';
import { InteractiveObject } from '../interaction/InteractiveObject';
import { InteractionManager } from '../interaction/InteractionManager';
import { TrainingState, type TrainingSnapshot } from '../training/TrainingState';
import { MissionManager } from '../training/MissionManager';
import { Mission2Manager } from '../training/Mission2Manager';
import { Mission3Manager } from '../training/Mission3Manager';
import { ContaminationManager } from '../training/ContaminationManager';
import { Mission4Manager } from '../training/Mission4Manager';
import { Mission5Manager } from '../training/Mission5Manager';
import { EventLog } from '../training/EventLog';
import { AssessmentManager } from '../training/AssessmentManager';
import { type WasteItem } from '../data/incident';
import { scenario } from '../data/scenario';
import { molecular } from '../data/molecular';
import { Laboratory } from '../world/Laboratory';
import { World } from '../world/World';
import { UIManager } from '../ui/UIManager';

export class App {
  private readonly canvas = document.createElement('canvas'); private readonly ui: UIManager; private world!: World; private player!: PlayerController; private interaction!: InteractionManager;
  private readonly state = new TrainingState(); private readonly mission = new MissionManager(this.state); private readonly mission2 = new Mission2Manager(this.state, scenario.sampleScenario); private readonly mission3 = new Mission3Manager(this.state); private readonly contamination = new ContaminationManager(this.state); private readonly mission4 = new Mission4Manager(this.state, scenario.molecularScenario); private readonly mission5 = new Mission5Manager(this.state); private readonly eventLog = new EventLog(); private readonly assessment = new AssessmentManager(); private previousSnapshot = this.state.snapshot; private previousTime = 0;
  constructor(private readonly container: HTMLElement | null) { if (!container) throw new Error('App container not found'); this.ui = new UIManager(container); }
  start(): void { this.ui.onStart(() => this.enterLaboratory()); }
  private enterLaboratory(): void { this.eventLog.start(); this.previousSnapshot = this.state.snapshot; this.canvas.className = 'scene'; this.container?.prepend(this.canvas); this.ui.showGame(); const laboratory = new Laboratory(); this.world = new World(this.canvas, laboratory); const collisions = new CollisionSystem(laboratory.collisions); this.player = new PlayerController(this.canvas, collisions); this.interaction = new InteractionManager(this.player.camera, (target) => this.ui.setTarget(target)); this.registerMission1Interactions(laboratory, collisions); let mission2 = false; let mission3 = false; let mission4 = false; let mission5 = false; this.state.subscribe((snapshot) => { this.trackState(snapshot); this.ui.setMission(snapshot); if (snapshot.mission1Completed && !mission2) { mission2 = true; this.registerMission2Interactions(laboratory); } if (snapshot.mission2Completed && !mission3) { mission3 = true; this.registerMission3Interactions(laboratory); } if (snapshot.mission3Completed && !mission4) { mission4 = true; this.registerMission4Interactions(laboratory); } if (snapshot.mission4Completed && !mission5) { mission5 = true; this.registerMission5Interactions(laboratory); } }); window.addEventListener('resize', () => this.world.resize(this.player.camera)); this.canvas.addEventListener('click', () => { this.ui.setPointerHint(false); this.player.focus(); }); document.addEventListener('pointerlockchange', () => this.ui.setPointerHint(document.pointerLockElement !== this.canvas)); window.addEventListener('keydown', (event) => { if (event.code === 'KeyE') this.interaction.interact(); }); this.ui.setPointerHint(true); this.world.resize(this.player.camera); requestAnimationFrame((time) => this.loop(time, laboratory)); }
  private registerMission1Interactions(laboratory: Laboratory, collisions: CollisionSystem): void { const [sign, prep, sink] = laboratory.interactive; this.interaction.register(sign.root, new InteractiveObject('safety-sign', 'Información del área', 'safety', 5, () => { this.openModal(); this.ui.showSafety(() => this.state.update({ riskInfoReviewed: true })); })); this.interaction.register(prep.root, new InteractiveObject('preparation-station', 'Estación de preparación', 'preparation', 4, () => { this.openModal(); this.ui.showPreparation(() => this.state.update({ preparationCompleted: true })); })); this.interaction.register(sink.root, new InteractiveObject('hand-washing', 'Estación de higiene de manos', 'hygiene', 4, () => { this.openModal(); this.ui.showHandHygiene(() => this.state.update({ handHygieneCompleted: true })); })); this.interaction.register(laboratory.doorRoot, new InteractiveObject('door', 'Puerta de ingreso', 'door', 4, () => { this.openModal(); this.ui.showDoor(this.state.snapshot, () => { if (this.mission.unlockDoor()) { collisions.removeObstacle(laboratory.doorCollision); laboratory.openDoor(); } }); })); }
  private registerMission2Interactions(laboratory: Laboratory): void { this.interaction.register(laboratory.sampleRoot, new InteractiveObject('sample', 'Muestra SIM-001', 'sample', 4, () => { this.openModal(); this.ui.showSample(() => { const result = this.mission2.inspectSample(); if (!result.success) this.ui.showInspectionBlocked(); }); })); this.interaction.register(laboratory.computerRoot, new InteractiveObject('computer', 'Sistema de información del laboratorio', 'computer', 4, () => { this.openModal(); this.ui.showComputer(scenario.sampleScenario, (decision) => { const result = this.mission2.verifySampleDecision(decision); if (!result.correct) this.eventLog.record({ type: 'wrong_decision', mission: 2, outcome: 'incorrect', critical: scenario.sampleScenario === 'mismatch' && decision === 'accept', description: 'Decisión incorrecta de recepción.' }); this.ui.showVerificationResult(result); }); })); }
  private registerMission3Interactions(laboratory: Laboratory): void { this.interaction.register(laboratory.cabinetRoot, new InteractiveObject('cabinet', 'Cabina de Seguridad Biológica', 'cabinet', 4, () => { this.openModal(); this.ui.showConceptReview('CABINA DE SEGURIDAD BIOLÓGICA', 'Equipo de contención primaria para medidas de control determinadas mediante evaluación de riesgo. Su uso depende del procedimiento institucional.', 'REGISTRAR RECONOCIMIENTO', () => { this.mission3.reviewCabinet(); this.checkMission3(); }); })); this.interaction.register(laboratory.pipetteRoot, new InteractiveObject('pipette', 'Micropipeta', 'pipette', 4, () => { this.openModal(); this.ui.showConceptReview('MICROPIPETA', 'Instrumento reconocido de forma conceptual dentro del flujo general de trabajo.', 'RECONOCIDA', () => { this.mission3.reviewPipette(); this.checkMission3(); }); })); this.interaction.register(laboratory.workAreaRoot, new InteractiveObject('work-area', 'Organización del área', 'work-area', 4, () => { this.openModal(); this.ui.showConceptReview('ORGANIZACIÓN DEL FLUJO', 'Recepción → Área de trabajo → Procesamiento conceptual → Análisis.', 'REVISAR ORGANIZACIÓN', () => { this.mission3.reviewWorkArea(); this.checkMission3(); }); })); this.interaction.register(laboratory.workSampleRoot, new InteractiveObject('work-sample', 'SIM-001 en área de trabajo', 'work-sample', 4, () => { this.openModal(); this.contamination.touchSample(); this.ui.showConceptReview('TRANSFERENCIA SIMULADA', 'La mano virtual interactuó con SIM-001. Aplique la medida institucional antes de tocar una superficie compartida.', 'CONTINUAR', () => undefined); })); this.interaction.register(laboratory.safetyMeasureRoot, new InteractiveObject('measure', 'Medida simulada', 'measure', 4, () => { this.openModal(); this.contamination.applySimulatedMeasure(); this.ui.showSafeFlow(() => undefined); })); this.interaction.register(laboratory.sharedSurfaceRoot, new InteractiveObject('keyboard', 'Teclado / superficie compartida', 'surface', 4, () => { this.openModal(); const result = this.contamination.touchSharedSurface(); if (result === 'contamination') { laboratory.showContamination(); this.eventLog.record({ type: 'contamination_detected', mission: 3, outcome: 'incorrect', critical: false, description: 'Contaminación cruzada simulada detectada.' }); this.ui.showContamination(() => { this.mission3.acknowledgeError(); this.checkMission3(); }); } else if (result === 'safe_flow') this.ui.showSafeFlow(() => this.checkMission3()); else this.ui.showConceptReview('SECUENCIA INCOMPLETA', 'Complete primero la secuencia con SIM-001 y la medida simulada.', 'CERRAR', () => undefined); })); }
  private registerMission4Interactions(laboratory: Laboratory): void { this.interaction.register(laboratory.molecularEquipmentRoot, new InteractiveObject('molecular-equipment', molecular.equipment, 'molecular', 4, () => { this.openModal(); this.ui.showMolecularRecognition(() => this.mission4.reviewArea()); })); this.interaction.register(laboratory.molecularTerminalRoot, new InteractiveObject('molecular-terminal', 'Iniciar análisis simulado', 'molecular-terminal', 4, () => { this.openModal(); this.ui.showMolecularStart(() => { if (this.mission4.startAnalysis()) this.ui.showAnalysisProgress(() => this.mission4.completeAnalysis()); else this.ui.showMolecularBlocked(); }); })); this.interaction.register(laboratory.molecularResultRoot, new InteractiveObject('molecular-result', 'Resultado molecular', 'result', 4, () => { this.openModal(); if (!this.mission4.canAccessResult()) this.ui.showMolecularBlocked(); else this.ui.showMolecularResult(scenario.molecularScenario, () => { if (this.mission4.reviewResult()) this.ui.showMolecularQuestion(scenario.molecularScenario, (answer) => { const result = this.mission4.interpret(answer); if (!result.correct) this.eventLog.record({ type: 'wrong_interpretation', mission: 4, outcome: 'incorrect', critical: scenario.molecularScenario === 'invalid', description: 'Interpretación molecular incorrecta.' }); this.ui.showMolecularInterpretation(result); if (result.correct) window.setTimeout(() => this.ui.showMission4Result(), 1200); }); else this.ui.showMolecularBlocked(); }); })); }
  private registerMission5Interactions(laboratory: Laboratory): void { this.interaction.register(laboratory.incidentRoot, new InteractiveObject('incident', 'Condición anormal detectada', 'incident', 4, () => { this.openModal(); this.ui.showIncident((decision) => { this.mission5.handleIncident(decision); if (decision === 'acknowledge') this.ui.showIncidentMessage('INCIDENTE RECONOCIDO', 'La condición anormal fue identificada. Detenga la actividad y reporte el evento.'); else { this.eventLog.record({ type: 'incident_ignored', mission: 5, outcome: 'incorrect', critical: true, description: 'Continuó o ignoró una condición anormal.' }); this.ui.showIncidentMessage('CONDUCTA INSEGURA REGISTRADA', 'La simulación registró que se continuó o ignoró una condición anormal.'); } }); })); this.interaction.register(laboratory.activityControlRoot, new InteractiveObject('activity', 'Control de actividad', 'activity', 4, () => { this.openModal(); this.ui.showConceptReview('CONTROL DE ACTIVIDAD', 'Detenga la actividad antes de continuar ante una condición anormal.', 'DETENER ACTIVIDAD', () => { const result = this.mission5.stopActivity(); if (!result.success) this.ui.showMission5Blocked('Reconozca el incidente antes de registrar la detención.'); }); })); this.interaction.register(laboratory.reportSystemRoot, new InteractiveObject('report', 'Sistema de reporte', 'report', 4, () => { this.openModal(); this.ui.showIncidentReport(() => { const result = this.mission5.reportIncident(); if (result.success) this.ui.showIncidentMessage('REPORTE REGISTRADO', 'El incidente fue registrado. Siga el procedimiento institucional correspondiente.'); else this.ui.showMission5Blocked(result.reason === 'incident_not_acknowledged' ? 'Reconozca el incidente antes de realizar el reporte.' : 'Detenga primero la actividad insegura antes de reportar.'); }); })); this.interaction.register(laboratory.emergencyStationRoot, new InteractiveObject('emergency', 'Estación de emergencia', 'emergency', 4, () => { this.openModal(); this.ui.showEmergency(() => this.mission5.reviewEmergencyStation()); })); this.interaction.register(laboratory.wasteRoot, new InteractiveObject('waste', 'Zona de residuos', 'waste', 4, () => { this.openModal(); this.runWasteExercise(); })); this.interaction.register(laboratory.closeoutRoot, new InteractiveObject('closeout', 'Verificación de cierre', 'closeout', 4, () => { this.openModal(); this.ui.showCloseout(this.state.snapshot, () => { if (this.mission5.confirmCloseout().success) this.ui.showFinalize(() => { const result = this.mission5.complete(); if (result.success) { this.ui.showMission5Complete(); window.setTimeout(() => { const assessment = this.assessment.assess(this.state.snapshot, this.eventLog.events); if (assessment) this.ui.showAssessment(assessment, this.eventLog.events, () => window.location.reload()); }, 600); } }); }); })); }
  private runWasteExercise(): void { const items: Array<[WasteItem, string]> = [['general_item', 'Material no contaminado'], ['simulated_biological_item', 'Material biológico SIMULADO'], ['simulated_sharps', 'Elemento cortopunzante SIMULADO']]; let index = 0; const next = (): void => { if (index >= items.length) { this.ui.showWasteComplete(); return; } const [item, label] = items[index]; this.ui.showWasteItem(label, (category) => { const result = this.mission5.classifyWaste(item, category); if (!result.correct) { this.eventLog.record({ type: 'wrong_waste_classification', mission: 5, outcome: 'incorrect', critical: false, description: 'Clasificación conceptual de residuo incorrecta.' }); this.ui.showWasteIncorrect(next); } else { index += 1; next(); } }); }; next(); }
  private checkMission3(): void { if (this.mission3.complete().success) this.ui.showMission3Result('MISIÓN 3 COMPLETADA'); }
  private trackState(snapshot: TrainingSnapshot): void { const fields: Array<[keyof TrainingSnapshot, 1 | 2 | 3 | 4 | 5, string]> = [['riskInfoReviewed', 1, 'Información de seguridad revisada.'], ['preparationCompleted', 1, 'Preparación completada.'], ['handHygieneCompleted', 1, 'Higiene de manos registrada.'], ['doorUnlocked', 1, 'Puerta habilitada.'], ['mission1Completed', 1, 'Misión 1 completada.'], ['sampleInspected', 2, 'SIM-001 inspeccionada.'], ['mission2Completed', 2, 'Misión 2 completada.'], ['biosafetyCabinetReviewed', 3, 'Cabina revisada.'], ['pipetteReviewed', 3, 'Micropipeta revisada.'], ['workAreaReviewed', 3, 'Organización revisada.'], ['workSampleContacted', 3, 'SIM-001 contactada.'], ['safeMeasureApplied', 3, 'Medida simulada aplicada.'], ['safeFlowCompleted', 3, 'Flujo seguro completado.'], ['crossContaminationAcknowledged', 3, 'Contaminación reconocida.'], ['mission3Completed', 3, 'Misión 3 completada.'], ['molecularAreaReviewed', 4, 'Área molecular revisada.'], ['molecularAnalysisStarted', 4, 'Análisis simulado iniciado.'], ['molecularAnalysisCompleted', 4, 'Análisis simulado completado.'], ['molecularResultReviewed', 4, 'Resultado revisado.'], ['mission4Completed', 4, 'Misión 4 completada.'], ['incidentDetected', 5, 'Incidente reconocido.'], ['incidentIgnored', 5, 'Incidente ignorado o conducta insegura registrada.'], ['unsafeActivityStopped', 5, 'Actividad detenida.'], ['incidentReported', 5, 'Incidente reportado.'], ['emergencyStationReviewed', 5, 'Estación de emergencia revisada.'], ['wasteClassificationCompleted', 5, 'Residuos completados.'], ['closeoutReviewed', 5, 'Cierre confirmado.'], ['mission5Completed', 5, 'Misión 5 completada.']]; fields.forEach(([key, mission, description]) => { if (!this.previousSnapshot[key] && snapshot[key]) this.eventLog.record({ type: String(key), mission, outcome: 'correct', critical: key === 'incidentIgnored', description }); }); this.previousSnapshot = snapshot; }
  private openModal(): void { this.player.release(); this.ui.setPointerHint(true); }
  private loop(time: number, laboratory: Laboratory): void { const delta = Math.min((time - this.previousTime) / 1000, 0.05); this.previousTime = time; this.player.update(delta); laboratory.update(delta); this.interaction.update(); if (!this.state.snapshot.mission1Completed && this.state.snapshot.doorUnlocked && this.player.camera.position.z > 16) { this.mission.markMissionComplete(); this.ui.showComplete(); } this.world.render(this.player.camera); requestAnimationFrame((next) => this.loop(next, laboratory)); }
}
